# Site
title: memememe
subtitle: memememememememememememe

# URL
url: http://memememememememe.me
baseurl: /
permalink: post/:title/

# Build settings
markdown: kramdown
port: 4444

# Jekyll
defaults:
  - 
    scope:
      path: ""
    values:
      cover: /assets/posts/the-stewart-platform/memememe2.jpg

# Data
social:
  facebook_url: "https://www.facebook.com/thiago.hersan"
  twitter_url: "https://www.twitter.com/thiagohersan"
  twitter_user: "@thiagohersan"
